---
config:
  layout: dagre
---
classDiagram
    direction TB
    class UserKind {
        common
        seller
    }
    <<enumeration>> UserKind

    class Seller {
    }

    class Common {
    }

    class User {
        -String id
        -String name
        -UserKind kind
        -String document_type
        -String document
        -String mail
        -String password
        -Wallet wallet
        +canTransfer() : Boolean
    }

    class LedgerEntryType {
        debit
        credit
    }
    <<enumeration>> LedgerEntryType

    class LedgerOperation {
      manual
      transfer
    }
    <<enumeration>> LedgerOperation

    class LedgerEntry {
        -UUID id
        -Wallet wallet
        -Transaction transaction
        -LedgerEntryType kind
      -LedgerOperation operation
        -float amount
    }

    class Wallet {
        -UUID id
        -String userId
        -float balance
        -List entries
        +debit(Money amount)
        +credit(Money amount)
    }

    class TransferStatus {
        pending
        authorized
        settled
        failed
    }
    <<enumeration>> TransferStatus

    class Transfer {
        -UUID id
        -TransferStatus status
        -User payer
        -User payee
        -float amount
    }

    <<enumeration>> TransferStatus

    User <|-- Seller
    User <|-- Common
    User --* UserKind : uses
    LedgerEntry --* LedgerEntryType : uses
    LedgerEntry --* LedgerOperation : uses
    Transfer --* TransferStatus : uses
    User "1" *-- "0..*" Wallet
    Wallet "1" -- "0..*" LedgerEntry
    Transfer "1" -- "1..*" LedgerEntry
    Transfer "1" -- "1" User : payer
    Transfer "1" -- "1" User : payee
